#ifndef _ADCMODULE_
#define  _ADCMODULE_

#include "saml21.h"

enum MeasurementType{SINGLE = 0,DIFFERENTIAL = 1};

enum MUXPOS{AIN0 = ADC_INPUTCTRL_MUXPOS_AIN0_Val , AIN1 = ADC_INPUTCTRL_MUXPOS_AIN1_Val , 
            AIN2 = ADC_INPUTCTRL_MUXPOS_AIN2_Val , AIN3 = ADC_INPUTCTRL_MUXPOS_AIN3_Val , AIN4 = ADC_INPUTCTRL_MUXPOS_AIN4_Val , 
            AIN5 = ADC_INPUTCTRL_MUXPOS_AIN5_Val , AIN6 = ADC_INPUTCTRL_MUXPOS_AIN6_Val , AIN7 = ADC_INPUTCTRL_MUXPOS_AIN7_Val , 
            AIN8 = ADC_INPUTCTRL_MUXPOS_AIN8_Val, AIN9 = ADC_INPUTCTRL_MUXPOS_AIN9_Val , AIN10 = ADC_INPUTCTRL_MUXPOS_AIN10_Val , 
            AIN11 = ADC_INPUTCTRL_MUXPOS_AIN11_Val , AIN12 = ADC_INPUTCTRL_MUXPOS_AIN12_Val , AIN13 = ADC_INPUTCTRL_MUXPOS_AIN13_Val , 
            AIN14 = ADC_INPUTCTRL_MUXPOS_AIN14_Val , AIN15 = ADC_INPUTCTRL_MUXPOS_AIN15_Val , AIN16 = ADC_INPUTCTRL_MUXPOS_AIN16_Val , 
            AIN17 = ADC_INPUTCTRL_MUXPOS_AIN17_Val , AIN18 = ADC_INPUTCTRL_MUXPOS_AIN18_Val , AIN19 = ADC_INPUTCTRL_MUXPOS_AIN19_Val , 
            AIN20 = ADC_INPUTCTRL_MUXPOS_AIN20_Val , AIN21 = ADC_INPUTCTRL_MUXPOS_AIN21_Val , AIN22 = ADC_INPUTCTRL_MUXPOS_AIN22_Val , 
            AIN23 = ADC_INPUTCTRL_MUXPOS_AIN23_Val , AINTEMP = ADC_INPUTCTRL_MUXPOS_TEMP_Val};

void initADC(enum MUXPOS);
double readAIN(enum MUXPOS);
double readRTD006(enum MUXPOS);
#endif